name: CI

on:
  workflow_call:
    inputs: {}
    secrets: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Setup Protoc Gen Go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Setup Protoc Gen TS
        run: npm install ts-protoc-gen

      - name: Generate
        run: make events
